namespace Car_trading_system.Forms
{
    partial class AdminHomeForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AdminHomeForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            this.SidebarTransition = new System.Windows.Forms.Timer(this.components);
            this.pnlMain = new System.Windows.Forms.Panel();
            this.sidePanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.menubtn = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.btnCustomers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnOrders = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnCarParts = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnCars = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuIconButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            this.sidePanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // SidebarTransition
            // 
            this.SidebarTransition.Interval = 10;
            this.SidebarTransition.Tick += new System.EventHandler(this.sideBarTransition_Tick);
            // 
            // pnlMain
            // 
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(277, 0);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Size = new System.Drawing.Size(1423, 741);
            this.pnlMain.TabIndex = 11;
            // 
            // sidePanel
            // 
            this.sidePanel.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.sidePanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sidePanel.BackgroundImage")));
            this.sidePanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.sidePanel.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.sidePanel.BorderRadius = 0;
            this.sidePanel.BorderThickness = 0;
            this.sidePanel.Controls.Add(this.bunifuButton21);
            this.sidePanel.Controls.Add(this.menubtn);
            this.sidePanel.Controls.Add(this.btnCustomers);
            this.sidePanel.Controls.Add(this.bunifuButton27);
            this.sidePanel.Controls.Add(this.btnOrders);
            this.sidePanel.Controls.Add(this.btnCarParts);
            this.sidePanel.Controls.Add(this.btnCars);
            this.sidePanel.Controls.Add(this.btnDashboard);
            this.sidePanel.Controls.Add(this.bunifuIconButton1);
            this.sidePanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.sidePanel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.sidePanel.Location = new System.Drawing.Point(0, 0);
            this.sidePanel.Name = "sidePanel";
            this.sidePanel.ShowBorders = true;
            this.sidePanel.Size = new System.Drawing.Size(277, 741);
            this.sidePanel.TabIndex = 10;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Log out";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Poppins SemiBold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton21.IdleBorderRadius = 1;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton21.IdleIconLeftImage = global::Car_trading_system.Properties.Resources.logout;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(0, 699);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.bunifuButton21.onHoverState.IconLeftImage = global::Car_trading_system.Properties.Resources.profile_user__1_;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.bunifuButton21.OnIdleState.IconLeftImage = global::Car_trading_system.Properties.Resources.logout;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.bunifuButton21.OnPressedState.IconLeftImage = global::Car_trading_system.Properties.Resources.profile_user__2_;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(277, 42);
            this.bunifuButton21.TabIndex = 161;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // menubtn
            // 
            this.menubtn.AllowAnimations = true;
            this.menubtn.AllowBorderColorChanges = true;
            this.menubtn.AllowMouseEffects = true;
            this.menubtn.AnimationSpeed = 200;
            this.menubtn.BackColor = System.Drawing.Color.Transparent;
            this.menubtn.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.menubtn.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.menubtn.BorderRadius = 1;
            this.menubtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.menubtn.BorderThickness = 1;
            this.menubtn.ColorContrastOnClick = 0;
            this.menubtn.ColorContrastOnHover = 0;
            this.menubtn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.menubtn.CustomizableEdges = borderEdges2;
            this.menubtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.menubtn.Image = global::Car_trading_system.Properties.Resources.burger_bar__1_;
            this.menubtn.ImageMargin = new System.Windows.Forms.Padding(0);
            this.menubtn.Location = new System.Drawing.Point(32, 0);
            this.menubtn.Name = "menubtn";
            this.menubtn.RoundBorders = true;
            this.menubtn.ShowBorders = true;
            this.menubtn.Size = new System.Drawing.Size(38, 38);
            this.menubtn.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.menubtn.TabIndex = 5;
            this.menubtn.Click += new System.EventHandler(this.menubtn_Click);
            // 
            // btnCustomers
            // 
            this.btnCustomers.AllowAnimations = true;
            this.btnCustomers.AllowMouseEffects = true;
            this.btnCustomers.AllowToggling = false;
            this.btnCustomers.AnimationSpeed = 200;
            this.btnCustomers.AutoGenerateColors = false;
            this.btnCustomers.AutoRoundBorders = false;
            this.btnCustomers.AutoSizeLeftIcon = true;
            this.btnCustomers.AutoSizeRightIcon = true;
            this.btnCustomers.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomers.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCustomers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomers.BackgroundImage")));
            this.btnCustomers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCustomers.ButtonText = "Customers";
            this.btnCustomers.ButtonTextMarginLeft = 0;
            this.btnCustomers.ColorContrastOnClick = 45;
            this.btnCustomers.ColorContrastOnHover = 45;
            this.btnCustomers.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnCustomers.CustomizableEdges = borderEdges3;
            this.btnCustomers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomers.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomers.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCustomers.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCustomers.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCustomers.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCustomers.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomers.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCustomers.IconMarginLeft = 11;
            this.btnCustomers.IconPadding = 10;
            this.btnCustomers.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCustomers.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCustomers.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCustomers.IconSize = 25;
            this.btnCustomers.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCustomers.IdleBorderRadius = 1;
            this.btnCustomers.IdleBorderThickness = 1;
            this.btnCustomers.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCustomers.IdleIconLeftImage = global::Car_trading_system.Properties.Resources.multiple_users_silhouette__1_;
            this.btnCustomers.IdleIconRightImage = null;
            this.btnCustomers.IndicateFocus = false;
            this.btnCustomers.Location = new System.Drawing.Point(32, 339);
            this.btnCustomers.Name = "btnCustomers";
            this.btnCustomers.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomers.OnDisabledState.BorderRadius = 1;
            this.btnCustomers.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCustomers.OnDisabledState.BorderThickness = 1;
            this.btnCustomers.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomers.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomers.OnDisabledState.IconLeftImage = null;
            this.btnCustomers.OnDisabledState.IconRightImage = null;
            this.btnCustomers.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCustomers.onHoverState.BorderRadius = 1;
            this.btnCustomers.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCustomers.onHoverState.BorderThickness = 1;
            this.btnCustomers.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCustomers.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.btnCustomers.onHoverState.IconLeftImage = global::Car_trading_system.Properties.Resources.multiple_users_silhouette__2_;
            this.btnCustomers.onHoverState.IconRightImage = null;
            this.btnCustomers.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCustomers.OnIdleState.BorderRadius = 1;
            this.btnCustomers.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCustomers.OnIdleState.BorderThickness = 1;
            this.btnCustomers.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCustomers.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCustomers.OnIdleState.IconLeftImage = global::Car_trading_system.Properties.Resources.multiple_users_silhouette__1_;
            this.btnCustomers.OnIdleState.IconRightImage = null;
            this.btnCustomers.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCustomers.OnPressedState.BorderRadius = 1;
            this.btnCustomers.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCustomers.OnPressedState.BorderThickness = 1;
            this.btnCustomers.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCustomers.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCustomers.OnPressedState.IconLeftImage = global::Car_trading_system.Properties.Resources.multiple_users_silhouette__2_;
            this.btnCustomers.OnPressedState.IconRightImage = null;
            this.btnCustomers.Size = new System.Drawing.Size(238, 42);
            this.btnCustomers.TabIndex = 4;
            this.btnCustomers.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomers.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCustomers.TextMarginLeft = 0;
            this.btnCustomers.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCustomers.UseDefaultRadiusAndThickness = true;
            this.btnCustomers.Click += new System.EventHandler(this.btnCustomers_Click);
            // 
            // bunifuButton27
            // 
            this.bunifuButton27.AllowAnimations = true;
            this.bunifuButton27.AllowMouseEffects = true;
            this.bunifuButton27.AllowToggling = false;
            this.bunifuButton27.AnimationSpeed = 200;
            this.bunifuButton27.AutoGenerateColors = false;
            this.bunifuButton27.AutoRoundBorders = false;
            this.bunifuButton27.AutoSizeLeftIcon = true;
            this.bunifuButton27.AutoSizeRightIcon = true;
            this.bunifuButton27.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton27.BackgroundImage")));
            this.bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.ButtonText = "";
            this.bunifuButton27.ButtonTextMarginLeft = 0;
            this.bunifuButton27.ColorContrastOnClick = 45;
            this.bunifuButton27.ColorContrastOnHover = 45;
            this.bunifuButton27.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.bunifuButton27.CustomizableEdges = borderEdges4;
            this.bunifuButton27.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton27.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton27.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton27.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton27.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton27.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton27.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton27.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton27.IconMarginLeft = 11;
            this.bunifuButton27.IconPadding = 10;
            this.bunifuButton27.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton27.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton27.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton27.IconSize = 25;
            this.bunifuButton27.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.IdleBorderRadius = 1;
            this.bunifuButton27.IdleBorderThickness = 1;
            this.bunifuButton27.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton27.IdleIconLeftImage")));
            this.bunifuButton27.IdleIconRightImage = null;
            this.bunifuButton27.IndicateFocus = false;
            this.bunifuButton27.Location = new System.Drawing.Point(32, 769);
            this.bunifuButton27.Name = "bunifuButton27";
            this.bunifuButton27.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton27.OnDisabledState.BorderRadius = 1;
            this.bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnDisabledState.BorderThickness = 1;
            this.bunifuButton27.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton27.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton27.OnDisabledState.IconLeftImage = null;
            this.bunifuButton27.OnDisabledState.IconRightImage = null;
            this.bunifuButton27.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton27.onHoverState.BorderRadius = 1;
            this.bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.onHoverState.BorderThickness = 1;
            this.bunifuButton27.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage")));
            this.bunifuButton27.onHoverState.IconRightImage = null;
            this.bunifuButton27.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.OnIdleState.BorderRadius = 1;
            this.bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnIdleState.BorderThickness = 1;
            this.bunifuButton27.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuButton27.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton27.OnIdleState.IconLeftImage")));
            this.bunifuButton27.OnIdleState.IconRightImage = null;
            this.bunifuButton27.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton27.OnPressedState.BorderRadius = 1;
            this.bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnPressedState.BorderThickness = 1;
            this.bunifuButton27.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.bunifuButton27.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton27.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage1")));
            this.bunifuButton27.OnPressedState.IconRightImage = null;
            this.bunifuButton27.Size = new System.Drawing.Size(42, 42);
            this.bunifuButton27.TabIndex = 3;
            this.bunifuButton27.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton27.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton27.TextMarginLeft = 0;
            this.bunifuButton27.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton27.UseDefaultRadiusAndThickness = true;
            // 
            // btnOrders
            // 
            this.btnOrders.AllowAnimations = true;
            this.btnOrders.AllowMouseEffects = true;
            this.btnOrders.AllowToggling = false;
            this.btnOrders.AnimationSpeed = 200;
            this.btnOrders.AutoGenerateColors = false;
            this.btnOrders.AutoRoundBorders = false;
            this.btnOrders.AutoSizeLeftIcon = true;
            this.btnOrders.AutoSizeRightIcon = true;
            this.btnOrders.BackColor = System.Drawing.Color.Transparent;
            this.btnOrders.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnOrders.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrders.BackgroundImage")));
            this.btnOrders.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrders.ButtonText = "Orders";
            this.btnOrders.ButtonTextMarginLeft = 0;
            this.btnOrders.ColorContrastOnClick = 45;
            this.btnOrders.ColorContrastOnHover = 45;
            this.btnOrders.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnOrders.CustomizableEdges = borderEdges5;
            this.btnOrders.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrders.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrders.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrders.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrders.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnOrders.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOrders.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnOrders.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrders.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrders.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOrders.IconMarginLeft = 11;
            this.btnOrders.IconPadding = 10;
            this.btnOrders.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrders.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrders.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrders.IconSize = 25;
            this.btnOrders.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnOrders.IdleBorderRadius = 1;
            this.btnOrders.IdleBorderThickness = 1;
            this.btnOrders.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnOrders.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOrders.IdleIconLeftImage")));
            this.btnOrders.IdleIconRightImage = null;
            this.btnOrders.IndicateFocus = false;
            this.btnOrders.Location = new System.Drawing.Point(32, 403);
            this.btnOrders.Name = "btnOrders";
            this.btnOrders.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrders.OnDisabledState.BorderRadius = 1;
            this.btnOrders.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrders.OnDisabledState.BorderThickness = 1;
            this.btnOrders.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrders.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrders.OnDisabledState.IconLeftImage = null;
            this.btnOrders.OnDisabledState.IconRightImage = null;
            this.btnOrders.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnOrders.onHoverState.BorderRadius = 1;
            this.btnOrders.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrders.onHoverState.BorderThickness = 1;
            this.btnOrders.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnOrders.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.btnOrders.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage2")));
            this.btnOrders.onHoverState.IconRightImage = null;
            this.btnOrders.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnOrders.OnIdleState.BorderRadius = 1;
            this.btnOrders.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrders.OnIdleState.BorderThickness = 1;
            this.btnOrders.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnOrders.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnOrders.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnOrders.OnIdleState.IconLeftImage")));
            this.btnOrders.OnIdleState.IconRightImage = null;
            this.btnOrders.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnOrders.OnPressedState.BorderRadius = 1;
            this.btnOrders.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrders.OnPressedState.BorderThickness = 1;
            this.btnOrders.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnOrders.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnOrders.OnPressedState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("resource.IconLeftImage3")));
            this.btnOrders.OnPressedState.IconRightImage = null;
            this.btnOrders.Size = new System.Drawing.Size(238, 42);
            this.btnOrders.TabIndex = 3;
            this.btnOrders.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOrders.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrders.TextMarginLeft = 0;
            this.btnOrders.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOrders.UseDefaultRadiusAndThickness = true;
            this.btnOrders.Click += new System.EventHandler(this.btnOrders_Click);
            // 
            // btnCarParts
            // 
            this.btnCarParts.AllowAnimations = true;
            this.btnCarParts.AllowMouseEffects = true;
            this.btnCarParts.AllowToggling = false;
            this.btnCarParts.AnimationSpeed = 200;
            this.btnCarParts.AutoGenerateColors = false;
            this.btnCarParts.AutoRoundBorders = false;
            this.btnCarParts.AutoSizeLeftIcon = true;
            this.btnCarParts.AutoSizeRightIcon = true;
            this.btnCarParts.BackColor = System.Drawing.Color.Transparent;
            this.btnCarParts.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCarParts.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCarParts.BackgroundImage")));
            this.btnCarParts.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarParts.ButtonText = "Car Parts";
            this.btnCarParts.ButtonTextMarginLeft = 0;
            this.btnCarParts.ColorContrastOnClick = 45;
            this.btnCarParts.ColorContrastOnHover = 45;
            this.btnCarParts.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnCarParts.CustomizableEdges = borderEdges6;
            this.btnCarParts.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCarParts.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCarParts.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCarParts.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCarParts.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCarParts.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCarParts.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCarParts.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCarParts.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCarParts.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCarParts.IconMarginLeft = 11;
            this.btnCarParts.IconPadding = 10;
            this.btnCarParts.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCarParts.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCarParts.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCarParts.IconSize = 25;
            this.btnCarParts.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCarParts.IdleBorderRadius = 1;
            this.btnCarParts.IdleBorderThickness = 1;
            this.btnCarParts.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCarParts.IdleIconLeftImage = global::Car_trading_system.Properties.Resources.setting__2_;
            this.btnCarParts.IdleIconRightImage = null;
            this.btnCarParts.IndicateFocus = false;
            this.btnCarParts.Location = new System.Drawing.Point(32, 275);
            this.btnCarParts.Name = "btnCarParts";
            this.btnCarParts.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCarParts.OnDisabledState.BorderRadius = 1;
            this.btnCarParts.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarParts.OnDisabledState.BorderThickness = 1;
            this.btnCarParts.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCarParts.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCarParts.OnDisabledState.IconLeftImage = null;
            this.btnCarParts.OnDisabledState.IconRightImage = null;
            this.btnCarParts.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCarParts.onHoverState.BorderRadius = 1;
            this.btnCarParts.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarParts.onHoverState.BorderThickness = 1;
            this.btnCarParts.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCarParts.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.btnCarParts.onHoverState.IconLeftImage = global::Car_trading_system.Properties.Resources.setting__4_;
            this.btnCarParts.onHoverState.IconRightImage = null;
            this.btnCarParts.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCarParts.OnIdleState.BorderRadius = 1;
            this.btnCarParts.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarParts.OnIdleState.BorderThickness = 1;
            this.btnCarParts.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCarParts.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCarParts.OnIdleState.IconLeftImage = global::Car_trading_system.Properties.Resources.setting__2_;
            this.btnCarParts.OnIdleState.IconRightImage = null;
            this.btnCarParts.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCarParts.OnPressedState.BorderRadius = 1;
            this.btnCarParts.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCarParts.OnPressedState.BorderThickness = 1;
            this.btnCarParts.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCarParts.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCarParts.OnPressedState.IconLeftImage = global::Car_trading_system.Properties.Resources.setting__4_;
            this.btnCarParts.OnPressedState.IconRightImage = null;
            this.btnCarParts.Size = new System.Drawing.Size(238, 42);
            this.btnCarParts.TabIndex = 3;
            this.btnCarParts.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCarParts.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCarParts.TextMarginLeft = 0;
            this.btnCarParts.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCarParts.UseDefaultRadiusAndThickness = true;
            this.btnCarParts.Click += new System.EventHandler(this.btnParts_Click);
            // 
            // btnCars
            // 
            this.btnCars.AllowAnimations = true;
            this.btnCars.AllowMouseEffects = true;
            this.btnCars.AllowToggling = false;
            this.btnCars.AnimationSpeed = 200;
            this.btnCars.AutoGenerateColors = false;
            this.btnCars.AutoRoundBorders = false;
            this.btnCars.AutoSizeLeftIcon = true;
            this.btnCars.AutoSizeRightIcon = true;
            this.btnCars.BackColor = System.Drawing.Color.Transparent;
            this.btnCars.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCars.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCars.BackgroundImage")));
            this.btnCars.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCars.ButtonText = "Cars";
            this.btnCars.ButtonTextMarginLeft = 0;
            this.btnCars.ColorContrastOnClick = 45;
            this.btnCars.ColorContrastOnHover = 45;
            this.btnCars.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCars.CustomizableEdges = borderEdges7;
            this.btnCars.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCars.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCars.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCars.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCars.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCars.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCars.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCars.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCars.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCars.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCars.IconMarginLeft = 11;
            this.btnCars.IconPadding = 10;
            this.btnCars.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCars.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCars.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCars.IconSize = 25;
            this.btnCars.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCars.IdleBorderRadius = 1;
            this.btnCars.IdleBorderThickness = 1;
            this.btnCars.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCars.IdleIconLeftImage = global::Car_trading_system.Properties.Resources.sports_car__1_;
            this.btnCars.IdleIconRightImage = null;
            this.btnCars.IndicateFocus = false;
            this.btnCars.Location = new System.Drawing.Point(32, 207);
            this.btnCars.Name = "btnCars";
            this.btnCars.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCars.OnDisabledState.BorderRadius = 1;
            this.btnCars.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCars.OnDisabledState.BorderThickness = 1;
            this.btnCars.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCars.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCars.OnDisabledState.IconLeftImage = null;
            this.btnCars.OnDisabledState.IconRightImage = null;
            this.btnCars.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCars.onHoverState.BorderRadius = 1;
            this.btnCars.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCars.onHoverState.BorderThickness = 1;
            this.btnCars.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCars.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.btnCars.onHoverState.IconLeftImage = global::Car_trading_system.Properties.Resources.sports_car__2_;
            this.btnCars.onHoverState.IconRightImage = null;
            this.btnCars.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCars.OnIdleState.BorderRadius = 1;
            this.btnCars.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCars.OnIdleState.BorderThickness = 1;
            this.btnCars.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnCars.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCars.OnIdleState.IconLeftImage = global::Car_trading_system.Properties.Resources.sports_car__1_;
            this.btnCars.OnIdleState.IconRightImage = null;
            this.btnCars.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCars.OnPressedState.BorderRadius = 1;
            this.btnCars.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCars.OnPressedState.BorderThickness = 1;
            this.btnCars.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnCars.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnCars.OnPressedState.IconLeftImage = global::Car_trading_system.Properties.Resources.sports_car__2_;
            this.btnCars.OnPressedState.IconRightImage = null;
            this.btnCars.Size = new System.Drawing.Size(238, 42);
            this.btnCars.TabIndex = 3;
            this.btnCars.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCars.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCars.TextMarginLeft = 0;
            this.btnCars.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCars.UseDefaultRadiusAndThickness = true;
            this.btnCars.Click += new System.EventHandler(this.btnCars_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "Dashboard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges8;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 25;
            this.btnDashboard.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnDashboard.IdleBorderRadius = 1;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnDashboard.IdleIconLeftImage = global::Car_trading_system.Properties.Resources.dashboard;
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(32, 134);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 1;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnDashboard.onHoverState.BorderRadius = 1;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(18)))), ((int)(((byte)(31)))));
            this.btnDashboard.onHoverState.IconLeftImage = global::Car_trading_system.Properties.Resources.dashboard__1_;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnDashboard.OnIdleState.BorderRadius = 1;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnDashboard.OnIdleState.IconLeftImage = global::Car_trading_system.Properties.Resources.dashboard;
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnDashboard.OnPressedState.BorderRadius = 1;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(250)))), ((int)(((byte)(171)))), ((int)(((byte)(111)))));
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(146)))), ((int)(((byte)(118)))), ((int)(((byte)(133)))));
            this.btnDashboard.OnPressedState.IconLeftImage = global::Car_trading_system.Properties.Resources.dashboard__1_1;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(238, 42);
            this.btnDashboard.TabIndex = 3;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            // 
            // bunifuIconButton1
            // 
            this.bunifuIconButton1.AllowAnimations = true;
            this.bunifuIconButton1.AllowBorderColorChanges = true;
            this.bunifuIconButton1.AllowMouseEffects = true;
            this.bunifuIconButton1.AnimationSpeed = 200;
            this.bunifuIconButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuIconButton1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuIconButton1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(20)))), ((int)(((byte)(29)))));
            this.bunifuIconButton1.BorderRadius = 1;
            this.bunifuIconButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            this.bunifuIconButton1.BorderThickness = 1;
            this.bunifuIconButton1.ColorContrastOnClick = 0;
            this.bunifuIconButton1.ColorContrastOnHover = 0;
            this.bunifuIconButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuIconButton1.CustomizableEdges = borderEdges9;
            this.bunifuIconButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuIconButton1.Image = global::Car_trading_system.Properties.Resources.racing;
            this.bunifuIconButton1.ImageMargin = new System.Windows.Forms.Padding(0);
            this.bunifuIconButton1.Location = new System.Drawing.Point(32, 52);
            this.bunifuIconButton1.Name = "bunifuIconButton1";
            this.bunifuIconButton1.RoundBorders = true;
            this.bunifuIconButton1.ShowBorders = true;
            this.bunifuIconButton1.Size = new System.Drawing.Size(38, 38);
            this.bunifuIconButton1.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            this.bunifuIconButton1.TabIndex = 0;
            // 
            // AdminHomeForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.ClientSize = new System.Drawing.Size(1700, 741);
            this.Controls.Add(this.pnlMain);
            this.Controls.Add(this.sidePanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(1718, 697);
            this.Name = "AdminHomeForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Admin Home";
            this.Load += new System.EventHandler(this.AdminHomeForm_Load);
            this.sidePanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton bunifuIconButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCars;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCarParts;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnOrders;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCustomers;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton menubtn;
        private Bunifu.UI.WinForms.BunifuPanel sidePanel;
        private System.Windows.Forms.Timer SidebarTransition;
        private System.Windows.Forms.Panel pnlMain;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
    }
}